on: [push]

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: "Check Installation"
        run: make check-python
      - name: "Run tests"
        run: make unit-tests
            

