on: [push]

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install system prerequisites"
        run: sudo make install-prereqs

      - name: "Install Python dependencies"
        run: make install

      - name: "Run tests"
        run: make unit-tests
            
